import Head from 'next/head'
import { NewsArticles, NewsResponse } from "@/models/NewsArticles"
import { GetServerSideProps } from "next"
import NewsArticleGrid from '@/components/NewsArticleGrid'
import { Heading } from "@chakra-ui/react";
// import Navbar from '@/components/Navbar';


// This page uses getServerSideProps to fetch data server-side on every request.
//           This allows search engines to crawl the page content and improves SEO.

interface NewsPageProps {
    newsArticles: NewsArticles[],
}

export const getServerSideProps: GetServerSideProps<NewsPageProps> = async () => {
    const response = await fetch("https://newsapi.org/v2/top-headlines?country=us&apiKey=" + process.env.NEWS_API_KEY);
    const newsResponse : NewsResponse = await response.json();
    return {
        props: {newsArticles : newsResponse.articles}
    }
}

export default function Home({newsArticles} : NewsPageProps) {
  return (
    <>
      <Head>
        <title key='title'>Breaking News</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.jpg" />
      </Head>
      <main>
       
        {/* <NewsPage newsArticles={[]}/> */}
        <Heading m="auto" alignItems={"center"} justifyContent="center" display="flex" color="red.300" mb="2">Breaking News</Heading>
        <NewsArticleGrid articles={newsArticles}/>
      </main>
    </>
  )
}
